name: fashop_ecommerce
description: A new Flutter project.




version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  carousel_pro_nullsafety: ^1.0.2
  lecle_flutter_carousel_pro: ^0.0.1
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  conditional_builder_null_safety: ^0.0.6
  hexcolor: ^2.0.7

  # firebase
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  firebase_storage: ^10.3.4
  google_sign_in: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/back.jpg
    - assets/images/c1.jpg
    - assets/images/google.png
    - assets/images/m1.jpeg
    - assets/images/m2.jpg
    - assets/images/w1.jpeg
    - assets/images/w3.jpeg
    - assets/images/w4.jpeg
    - assets/images/cats/accessories.png
    - assets/images/cats/dress.png
    - assets/images/cats/formal.png
    - assets/images/cats/informal.png
    - assets/images/cats/jeans.png
    - assets/images/cats/shoe.png
    - assets/images/cats/tshirt.png
    - assets/images/products/blazer1.jpeg
    - assets/images/products/blazer2.jpeg
    - assets/images/products/dress1.jpeg
    - assets/images/products/dress2.jpeg
    - assets/images/products/hills1.jpeg
    - assets/images/products/hills2.jpeg
    - assets/images/products/pants2.jpeg
    - assets/images/products/skt1.jpeg
    - assets/images/products/skt2.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

